// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('SimpleRegistration', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('SimpleRegistration', async function() {
    await driver.get("https://rori4.github.io/selenium-practice/")
    await driver.manage().window().setRect(1296, 696)
    await driver.findElement(By.css(".ng-tns-c6-0 > .menu-title")).click()
    await driver.findElement(By.id("email")).sendKeys("admin@admin.com")
    await driver.findElement(By.id("password")).sendKeys("123124")
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
  })
})
